api version: v1
kind: Dep[loyment
metadata: 
   name: app1nginx-deployment
   labels:
      app: app1-nginx
spec:
   replicas: 1
   selector:
      matchLabels:
        app: app1-nginx
   templates:
      metadata:
         labels:
           app: app1-nginx
      spec:
         containers:
           - name: app1-nginx
             image: stacksimplify/kube-nginxapp1:1.0.0
             ports:
               - containerPort: 80