apiVersion: v1
kind: Service
metadata:
   name: azure-file-nginx-service
   labels:
     app: azure-files-nginx-app
spec:
  type: LoadBalancer
  selector:
    app: azure-file-nginx-app
  ports:
    -port: 90
     targetPort: 80
  